/**
 * A curated, hardcoded set of common emoji — no external emoji-data
 * package (matches this project's zero-runtime-dependency constraint).
 * Each entry's `name` doubles as its slash-command label/search keyword;
 * `keywords` adds a couple of common synonyms so "/fire", "/heart", etc.
 * find the right one directly, without having to type "/emoji" first.
 */
export const EMOJI_LIST = [
  { char: '😀', name: 'grinning face', keywords: ['smile', 'happy'] },
  { char: '😂', name: 'face with tears of joy', keywords: ['laugh', 'lol'] },
  { char: '😍', name: 'heart eyes', keywords: ['love', 'crush'] },
  { char: '😎', name: 'cool', keywords: ['sunglasses'] },
  { char: '🤔', name: 'thinking face', keywords: ['hmm'] },
  { char: '😉', name: 'winking face', keywords: ['wink'] },
  { char: '😢', name: 'crying face', keywords: ['sad', 'tear'] },
  { char: '😡', name: 'angry face', keywords: ['mad', 'rage'] },
  { char: '😱', name: 'screaming face', keywords: ['shock', 'scared'] },
  { char: '🥳', name: 'party face', keywords: ['celebrate', 'birthday'] },
  { char: '🙏', name: 'folded hands', keywords: ['please', 'pray', 'thanks'] },
  { char: '👍', name: 'thumbs up', keywords: ['approve', 'yes', 'like'] },
  { char: '👎', name: 'thumbs down', keywords: ['disapprove', 'no'] },
  { char: '👏', name: 'clapping hands', keywords: ['applause', 'congrats'] },
  { char: '🙌', name: 'raised hands', keywords: ['hooray', 'yay'] },
  { char: '👋', name: 'waving hand', keywords: ['hello', 'bye'] },
  { char: '✌️', name: 'victory hand', keywords: ['peace'] },
  { char: '💪', name: 'flexed biceps', keywords: ['strong', 'muscle'] },
  { char: '🤝', name: 'handshake', keywords: ['deal', 'agree'] },
  { char: '❤️', name: 'red heart', keywords: ['love'] },
  { char: '🔥', name: 'fire', keywords: ['hot', 'lit'] },
  { char: '⭐', name: 'star', keywords: ['favorite'] },
  { char: '✨', name: 'sparkles', keywords: ['shiny', 'magic'] },
  { char: '🎉', name: 'party popper', keywords: ['celebrate', 'congrats'] },
  { char: '🎊', name: 'confetti ball', keywords: ['celebrate'] },
  { char: '💡', name: 'light bulb', keywords: ['idea', 'tip'] },
  { char: '✅', name: 'check mark', keywords: ['done', 'yes', 'complete'] },
  { char: '❌', name: 'cross mark', keywords: ['no', 'wrong', 'delete'] },
  { char: '⚠️', name: 'warning', keywords: ['caution', 'alert'] },
  { char: '❓', name: 'question mark', keywords: ['question', 'help'] },
  { char: '❗', name: 'exclamation mark', keywords: ['important', 'alert'] },
  { char: '🚀', name: 'rocket', keywords: ['launch', 'fast', 'ship'] },
  { char: '🐛', name: 'bug', keywords: ['bug', 'issue'] },
  { char: '🔧', name: 'wrench', keywords: ['fix', 'tool', 'settings'] },
  { char: '📌', name: 'pushpin', keywords: ['pin', 'note'] },
  { char: '📎', name: 'paperclip', keywords: ['attachment', 'clip'] },
  { char: '📅', name: 'calendar', keywords: ['date', 'schedule'] },
  { char: '⏰', name: 'alarm clock', keywords: ['time', 'reminder'] },
  { char: '📈', name: 'chart increasing', keywords: ['growth', 'stats'] },
  { char: '📉', name: 'chart decreasing', keywords: ['decline', 'stats'] },
  { char: '💰', name: 'money bag', keywords: ['money', 'cash'] },
  { char: '💬', name: 'speech balloon', keywords: ['comment', 'chat'] },
  { char: '📝', name: 'memo', keywords: ['note', 'write'] },
  { char: '📚', name: 'books', keywords: ['reading', 'docs'] },
  { char: '🔗', name: 'link', keywords: ['url', 'chain'] },
  { char: '🔒', name: 'locked', keywords: ['private', 'secure'] },
  { char: '🔑', name: 'key', keywords: ['password', 'access'] },
  { char: '☕', name: 'coffee', keywords: ['coffee', 'break'] },
  { char: '🍕', name: 'pizza', keywords: ['food'] },
  { char: '🎂', name: 'birthday cake', keywords: ['birthday', 'cake'] },
  { char: '🎁', name: 'gift', keywords: ['present'] },
  { char: '🌟', name: 'glowing star', keywords: ['star', 'shiny'] },
  { char: '🌈', name: 'rainbow', keywords: ['colorful'] },
  { char: '☀️', name: 'sun', keywords: ['sunny', 'weather'] },
  { char: '🌧️', name: 'rain cloud', keywords: ['rainy', 'weather'] },
  { char: '🐶', name: 'dog face', keywords: ['dog', 'pet'] },
  { char: '🐱', name: 'cat face', keywords: ['cat', 'pet'] },
  { char: '🌍', name: 'globe', keywords: ['world', 'earth'] },
  { char: '🎯', name: 'direct hit', keywords: ['target', 'goal'] },
  { char: '🏆', name: 'trophy', keywords: ['win', 'award'] },
  { char: '🕐', name: 'clock', keywords: ['time'] },
  { char: '📣', name: 'megaphone', keywords: ['announce', 'shout'] },
  { char: '🧠', name: 'brain', keywords: ['smart', 'idea', 'mind'] },
  { char: '👀', name: 'eyes', keywords: ['look', 'watching'] },
];
